package kls.tgb.dto.sm;

public enum StartCommandState {
    STATE_NOT_EXISTS,
    WAITING_FOR_NAME,

    USER_EXISTS,
    NEW_USER_REGISTERED,

    PROJECT_EXISTS,
    PROJECT_NOT_EXISTS,

    BLANK_PROJECT_CREATED,
    PROJECT_CREATED
}
