spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tgb_bot
    username: postgres
    password: ${BD_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/changelog-root.yml
    default-schema: public
    user: postgres
    password: ${BD_PASS}
    url: jdbc:postgresql://localhost:5432/tgb_bot
    drop-first: true

telegram:
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_NAME}
  handler:
    description:
      start: приветствие, создание / изменение пользователя
      remove: обнуляет состояние проектов
      add_expense: добавляет расход
      all_expenses: все расходы

logging:
  level:
    kls:
      tgb:
        service: DEBUG
    root: INFO
    org.springframework.transaction.interceptor: TRACE
    org.hibernate.engine.transaction: DEBUG